version = 1

# JavaScript Analyzer
[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "browser",
    "nodejs",
    "vitest"
  ]

# Test Coverage Analyzer
[[analyzers]]
name = "test-coverage"
enabled = true
